import Head from "next/head";

import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Container, ListItem, UnorderedList } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className>
        <Container my={7} maxW="container.lg">
          <UnorderedList>
            <ListItem>
              <Link href="/trending">
                <a>trending issues</a>
              </Link>
            </ListItem>
            <ListItem>
              <Link href="/pending">
                <a>needs response</a>
              </Link>
            </ListItem>
          </UnorderedList>
        </Container>
      </main>
    </div>
  );
}
